[platformio]
default_envs = m5stack-cores3
src_dir = src

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv
lib_deps =
  m5stack/M5Unified @ 0.2.20
  gilmaimon/ArduinoWebsockets @ ^0.5.4
  bblanchon/ArduinoJson @ ^7.0.0
  m5stack/M5StackChan @ ^1.0.1
build_flags =
  -I .
  -D CORE_DEBUG_LEVEL=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
